name = "broider-gallery"
main = "server.ts"
compatibility_date = "2024-12-01"
account_id = "f4180fc950d4f7b314a000fbeb8af92a"

[[d1_databases]]
binding = "DB"
database_name = "broider-gallery"
database_id = "233ff50f-94e6-45bb-bb30-c519ff9bf28c"
